### ISSUE TITLE
Create an entity-row as well

### ISSUE THREAD

**Issue by igorsantos07** [amitfin/lovelace-daily-schedule-card#1]
This card is very handy, indeed! However, it would be even greater if it was possible to integrate it in an Entities card, thus having these functions on an entity-row instead of a fully fledged card :)

**Comment by amitfin** [comment]
@igorsantos07, I agree with you that integrating it with [the entities card](https://www.home-assistant.io/dashboards/entities/) could have been better, but I don't think it's possible. AFAIK, it's only possible to extend Home Assistant frontend with new cards. But, I would be happy to learn that it's possible if you can point me to an example or documentation.

**Comment by amitfin** [comment]
Done.
V1.2.0 supports embedding the component inside the Entities card.
Thanks!
