### ISSUE TITLE
Option for disable any time frame

### ISSUE THREAD

**Issue by michapr** [amitfin/lovelace-daily-schedule-card#2]
Hi,
Thanks for the card, is working great and is a nice help to manage timers.

Would be nice to have the option in settings to disable any of the saved time frames without deleting it.

Sometimes I need to change the irrigation (as sample) in spring/summer/autumn or any illumination and would like to use the same timer for all seasons.

What do you think?
(BTW: why the seconds are not available in settings? Any missed option from my side?)

Thanks!

**Comment by amitfin** [comment]
Thanks @michapr for the feedback!

It's possible to add a "disable-range" option. It'll require also changes in the daily-schedule integration component (the backend) for saving this new option, and not only this card element (the frontend).
The main concern is that it might complicate the user experience of the dialog with a feature that is not used so often. BTW, this is also the reason that seconds are not displayed. Seconds are supported by the backend, so adding them is a frontend-only change.

Can you elaborate why it's better to use the same timer for all seasons, versus having a few fixed timers for the different seasons and picking the correct one as needed?
Here is a design option for making the select process more convenient:
1. Create a [Dropbox helper](https://www.home-assistant.io/integrations/input_select/) entity (e.g. "input_select.irrigation_timer") where the options are the entity IDs of the per-season daily-schedule entities. (note: It's possible to create a more descriptive options by adding more logic in the template below, but not sure if it's really needed).
2. Create the following template entity, which should be the only one used in the automation rule(s) ("sensor.irrigation_timer"):
```
template:
  - sensor:
    - name: irrigation timer
      state: "{{ states(states('input_select.irrigation_timer')) }}"
```

**Comment by michapr** [comment]
Hi,
thanks for your answer.
I have a big number of switches / valves and would be fine to have for every device one timer only - it's more logical (for me ;-) ..) 

I'm coming from Domoticz (3 years ago) what I was using a long time - here every switch have a device "property"
As sample:
![grafik](https://github.com/amitfin/lovelace-daily-schedule-card/assets/11854556/5b78f82b-82e6-4e4b-b5f6-44b2b1c0c34b)

![grafik](https://github.com/amitfin/lovelace-daily-schedule-card/assets/11854556/a244d92e-d907-44df-842f-91b86b005d9b)

It's very comfortable and good for an overview - what time frame is active - and it is easy to enable/disable any action.

I do not think "that it might complicate the user experience of the dialog" - if to add an option field "disable" and grey it out.
In overview (card element) it will not be shown - so no confusion, I think so.

It would allow to add one scheduler for each element/group for different situations/seasons.

Thanks!
Michael

**Comment by amitfin** [comment]
Added the option to disable / enable a time range.
The minimum versions for this feature are:
- [Daily-schedule integration](https://github.com/amitfin/daily_schedule): [v1.5.1](https://github.com/amitfin/daily_schedule/releases/tag/v1.5.1)
- [Daily-schedule lovelace card](https://github.com/amitfin/lovelace-daily-schedule-card): [v1.4.0 ](https://github.com/amitfin/lovelace-daily-schedule-card/releases/tag/v1.4.0)

![image](https://github.com/amitfin/lovelace-daily-schedule-card/assets/19599059/25fa418d-c1f9-4ca0-aea8-5b8ee871d363)
