### ISSUE TITLE
Ways to simplify interface with many time slots?

### ISSUE THREAD

**Issue by igorsantos07** [amitfin/lovelace-daily-schedule-card#3]
This is more of a brainstorm than anything else, since I'm not sure exactly the best approach here...

The thing is: I use the daily schedule to configure moments to feed my cats, with 2 hours of interval. The time the sensor is `on` is irrelevant, I just need it to toggle so the automation fires, and thus I have all those periods with 1min between them. However, having 9 different times makes the use in the interface _very_ bulky.

I created a template that simplifies this listing (compare them below), but then, I cannot use it in conjunction with this card - which is awesome for editing the schedule, without having to go deep into the HA settings.

![image](https://github.com/amitfin/lovelace-daily-schedule-card/assets/532299/1e7cc21e-99e2-469f-9354-c66df41cd1d2)

Some ideas I had so far:
- allow a custom template for rendering each time block
- allow a custom content/template for the whole data
- add different settings to display the time blocks (e.g. hide end time, show only hours, or potentially both options)
- allow the edit popup to have its own URL, so we can create a button that navigates to it

Bonus: not sure if 12/24H has any affect on how the times are displayed, but I guess it should? I'm fine with 24h, though haha

------------
btw, don't you have any ko-fi or the likes? I now realise how you simplified a LOT my feeding routing and I wanted to pay you a beverage (hopefully with no cat hair LOL), at least :)

**Comment by amitfin** [comment]
Done in [v1.5.0](https://github.com/amitfin/lovelace-daily-schedule-card/releases/tag/v1.5.0).
Example:
```
- entity: binary_sensor.let_the_dog_out
  template: >-
    {{ state_attr(entity_id, 'schedule') | map(attribute='from') |
    map('truncate', 2, True, '') | join(' | ') }}
```

**Comment by igorsantos07** [comment]
You're awesome! Where's your ko-fi, or stuff like that? :)

BTW, not entirely sure why, but my HA didn't like how you broke that template into lines haha
I used it this way instead (which is waaaaaaaaay cleaner than my original for loop! thanks!):
```
      {{ state_attr(entity_id, 'schedule') 
        | rejectattr('disabled', 'true') 
        | map(attribute='from') 
        | map('truncate', 2, True, '')     
        | join(' | ') }}
```

**Comment by amitfin** [comment]
https://ko-fi.com/amitfinkelstein
